### ISSUE TITLE
[Web] Section `Join Tempus DAO`

### ISSUE THREAD

**Issue by danieledamiani** [tempusfinance/tempus-app#1918]
- Join Tempus DAO (design and text confirmed)
 - simple links

![Image](https://user-images.githubusercontent.com/25841025/175962023-163942cb-314b-4d23-9098-974956faf45c.png)

**Comment by irinelT** [comment]
On the website DAO is replaced with Community and Web3 with DeFi as I highlighted in the screenshot.
![JoinTheTempusCommunity](https://user-images.githubusercontent.com/98878781/183419468-fa0f101b-3cad-46c1-94cc-1fc85d58c552.png)

**Comment by lazarmitic** [comment]
Yes, this is intentionally changed.

**Comment by irinelT** [comment]
I guess this tempus-app requirement goes for tempus-web too.
https://github.com/tempusfinance/tempus-app/pull/2207
