### ISSUE TITLE
[Web] Legal pages

### ISSUE THREAD

**Issue by lazarmitic** [tempusfinance/tempus-app#2036]
Legal pages include:
1. Terms of Service
2. Privacy Policy
3. Disclaimer

**Comment by irinelT** [comment]
@lazarmitic Now the Admin column includes:

Admin

* [Branding](https://github.com/tempus-finance/branding-assets)
* [Terms](https://stage-tempus.web.app/terms#top)
* [Disclaimer](https://stage-tempus.web.app/disclaimer#top)
* [Privacy](https://stage-tempus.web.app/privacy#top)

Is this okay?
