### ISSUE TITLE
[Web] Footer improvement

### ISSUE THREAD

**Issue by danieledamiani** [tempusfinance/tempus-app#2046]
- [ ] ~Should we rename `Team` to `Contributors`?~
- [x] Clicking on internal link should navigate to that page and then scroll it to the top
- [x] Links to `#` need to be fixed
- [x] Is `Tempus Labs` redundant?
- [x] `We're hiring`, aren't we? (no jobs available)

iPad portrait
- [x] Set links on 4 columns

iPhone portrait
- [x] Set links on 2 columns

**Comment by RTP2016** [comment]
Should we rename Team to Contributors? Let's keep Team for now. 
Is Tempus Labs redundant? Yes, agree. 
We're hiring, aren't we? (no jobs available). Think it's best to reword to 'Jobs' or 'Careers'
