### ISSUE TITLE
[Web] `Team` page improvements

### ISSUE THREAD

**Issue by danieledamiani** [tempusfinance/tempus-app#2047]
- [x] Header text to be dark
- [x] Category title (`Founders` ...) needs more space at the bottom
- [x] `Our team has worked with some of the world's leading organizations` looks like the team partnered with the companies just below. Maybe a rewording?
- [ ] ~Remove line just above company logos~

In iPhone portrait

- [x] Reduce header font size

**Comment by RTP2016** [comment]
How about 
Our team has experience from working with some of the world's leading organizations ?
