### ISSUE TITLE
[Web] Token holder count does not include holders from Fantom network

### ISSUE THREAD

**Issue by lazarmitic** [tempusfinance/tempus-app#2095]

**Comment by irinelT** [comment]
Our UI
![Image](https://github.com/tempusfinance/tempus-app/assets/98878781/be2db53b-ff5e-4309-9f4d-fd14c647e210)


Fantom
![Image](https://github.com/tempusfinance/tempus-app/assets/98878781/1e21e154-c02d-4311-9a77-6b658e29d44b)


Ether
![Image](https://github.com/tempusfinance/tempus-app/assets/98878781/a62108db-9b24-4752-82a6-c5dc9b4ed608)
