### ISSUE TITLE
[Web] mobile cards for blog and products

### ISSUE THREAD

**Issue by ShawTim** [tempusfinance/tempus-app#2120]
![image](https://user-images.githubusercontent.com/85455/177986007-28f0e193-0be4-4637-b4bd-cd20e8cc2a28.png)

**Comment by irinelT** [comment]
Looks good.

![MobileCardsForBlogAndProducts](https://user-images.githubusercontent.com/98878781/221166043-a31cf163-2ec8-4b80-a1a8-c9fc4c8fc901.png)
