### ISSUE TITLE
[web] the token release chart should match the text description above to 1bn + consistent labels

### ISSUE THREAD

**Issue by yarmun** [tempusfinance/tempus-app#2194]
On: https://stage-tempus.web.app/token

1) The line chart should end at 1 billion tokens as per the description above, currently it is ending around 500m which can cause confusion.  Suspect the "Treasury & Liquidity Incentives" component is missing, should be added to the base.
![image](https://user-images.githubusercontent.com/39115449/178407202-71dd74bf-f1de-4abf-91cb-cf204a53f774.png)

2) The pie chart uses different labels names vs the stack chart above.  The namings should be adjusted to be consistent.
![image](https://user-images.githubusercontent.com/39115449/178407478-38467ec4-2369-46c1-b1ab-63afbf755c8a.png)

**Comment by RTP2016** [comment]
Correct labels: 
- Fair Launch Investors
- Investors & Advisors
- Current & Future Team
- Treasury & Liquidity Incentives

Need to add the Treasury & Liquidity Incentives to the base of chart 1. Let @Olafkuusik know if you need the image.

**Comment by danieledamiani** [comment]
As discussed, we only change the pie chart labels to be consistent with the supply chart

**Comment by irinelT** [comment]
Looks good.

![TheTokenReleaseChartShouldMatchTheTextDescriptionAbove](https://user-images.githubusercontent.com/98878781/221166619-3c538842-7885-4e58-b3f4-3935dddd0c6e.png)
